name: Gotext build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.27.0'
      id: go

    - name: Get dependencies
      run: |
        go mod download

    - name: Build package
      run: go build -mod=readonly -v .

    - name: Test
      run: go test -mod=readonly -v -race ./...

    - name: Install xgotext CLI
      run: go install -v github.com/leonelquinteros/gotext/cli/xgotext

    - name: Run xgotext CLI
      run: go run cli/xgotext/main.go -default test -in cli/xgotext/fixtures -out cli/xgotext/fixtures/out
      